### PR TITLE
Add Italian Translation

### PR DESCRIPTION
**Pull request by badjem79**

### CODE REVIEW

**Comment by brunobord** [comment]
I see this is a Work In Progress: fine, fine, fine.
Don't hesitate to ping me when you think it's okay to review. :)

**Comment by badjem79** [comment]
I need to read both of the files one more time to fix typos etc, I will let you know...

**Comment by brunobord** [comment]
any status update about this? did you manage to fix all your typos?

**Comment by badjem79** [comment]
yes, the typos whud be fixed

**Comment by brunobord** [comment]
right, cool, I'll start integrating as soon as I can, thank you for your hard work!

**Comment by brunobord** [comment]
- [ ] New directory with the new language name,
    - [ ] the black hack translation file name **must be** `the-black-hack.md`
    - [ ] For other files they can be named as you want, but they must have a `.md` extension **and** be referenced in the `meta.yaml` file
    - [ ] the `meta.yaml`
      - [ ] should mention the language name,
      - [ ] you must add the files you've translated with the *version of the translation* (if it's the first one, '1.0' is fine)
      - [ ] the name of the authour is the name of the translator,
    - [ ] You *may* add a README.md to explain things, thank people, give yourself credits, etc.
- [ ] You **must** add your contribution to the LICENSE file, in the last section.
- [ ] You *may* add a line in the changelog describing your contribution.
- [ ] Have a look at the section [Specific styles](https://github.com/brunobord/the-black-hack/blob/master/README.md#specific-styles). If you don't know how to handle it, leave it away, the maintainer will provide help.

**Pull request merged**
