### PR TITLE
last fixes

### PR DESCRIPTION
**Pull request by fermcg**
TODO for @brunobord

- [x] check build on this branch
- [x] add a line in the changelog.

### CODE REVIEW

**Comment by brunobord** [comment]
looks fine. I'll merge and push it on the website as soon as I can.

**Comment by brunobord** [comment]
edited the PR description with a checkbox for myself.

**Comment by fermcg** [comment]
thanks!

**Comment by brunobord** [comment]
merged and pushed on the website, you can announce it to your fellow OSR fans.

**Comment by fermcg** [comment]
Thanks Bruno!

By the way. I was just starting to isolate Rad Hack's english text.

I've seen you are doing it officially. Do you want help?

**Comment by brunobord** [comment]
> I've seen you are doing it officially. Do you want help?

let's talk about this here: https://github.com/brunobord/rad-hack/issues/1

**Pull request merged**
